# Generated by Django 5.0.14 on 2025-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(unique=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_card_no', models.CharField(max_length=20, unique=True)),
                ('operator_name', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MACHINE_ID', models.IntegerField()),
                ('LINE_NUMBER', models.IntegerField()),
                ('OPERATOR_ID', models.CharField(max_length=30)),
                ('DATE', models.DateField(db_index=True)),
                ('START_TIME', models.TimeField()),
                ('END_TIME', models.TimeField()),
                ('MODE', models.IntegerField(db_index=True)),
                ('OPERATION_COUNT', models.IntegerField()),
                ('SKIP_COUNT', models.FloatField()),
                ('NEEDLE_STOPTIME', models.FloatField()),
                ('Tx_LOG_ID', models.IntegerField()),
                ('STORED_LOG_ID', models.IntegerField()),
                ('DEVICE_ID', models.IntegerField()),
                ('RESERVE', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['DATE'], name='logs_machin_DATE_2807c4_idx'), models.Index(fields=['created_at'], name='logs_machin_created_496429_idx'), models.Index(fields=['MODE'], name='logs_machin_MODE_b3338b_idx')],
            },
        ),
    ]
