# Generated by Django 5.0.14 on 2025-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelog',
            name='MODE',
            field=models.IntegerField(),
        ),
    ]
